### ISSUE TITLE
`halem` command

### ISSUE THREAD

**Issue by SiggyF** [TUDelft-CITG/Route_optimization_in_dynamic_currents#1]
This package [installs](https://github.com/TUDelft-CITG/Route_optimization_in_dynamic_currents/blob/master/setup.py#L70) the command line program `halem`. But this program is not yet implemented. 

Are you planning to create a command line interface to your software? Or is it intended to be a library?

**Comment by Pietervanhalem** [comment]
Hi Fedor,

thanks for your feedback. I am not aware of any command line interfaces. I think I copied this from OpenCLSim when I created this file. I Think you refer to these lines in the setup.py:

    entry_points={
        'console_scripts': [
            'halem=halem.cli:cli',
        ],
    },

can I just remove these lines?

**Comment by SiggyF** [comment]
Yes you can remove that part. In case you want to re-add it later, it is described in the [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) manual.

**Comment by Pietervanhalem** [comment]
This Issue is fixed in commit 'command_line_issue' in the developer's branch and will soon be merged with the master
